name: xraytest

on:
  workflow_dispatch:
    inputs:
      UrlEnvironment:
        description: 'URL of the environment to use'
        required: true
        default: 'https://example.com'

jobs:
  test-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Show URL Environment Input
        run: echo "The URL Environment parameter is: ${{ inputs.UrlEnvironment }}"
